# Generated by Django 2.2.6 on 2019-12-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('desg', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
